model:
  path: models/yolo.pt

data:
  frame_dir: data/test/frames  

position:
  path: veri/pozisyonlar.json  # pozisyon verisinin yeri

output:
  dir: output/
  result_json: output/result.json
